#model selection------------------------------------------------------------------------------------------------------------
test_case: "rjpbl"
#specific TC test case used, options: "rjpbl"

grid: "interp_latlon"
#grid used in analysis, options: "interp_latlon"

resolution: "50km"
#horizontal resolution of the 

#preprocessing--------------------------------------------------------------------------------------------------------------

all_models: False
#use all models or not

models: ["fv3_dzlow"]
#custom list of models, use with all_models setting

vars: ["U", "V"]
#list of variables

val: [100.0, 150.0, 200.0, 250.0, 500.0, 1000.0, 1500.0, 2000.0, 3000.0, 4000.0, 5000.0, 6000.0, 7000.0, 8000.0, 9000.0, 
      10000.0, 11000.0, 12000.0, 13000.0, 14000.0, 15000.0, 16000.0]
#value/values list for interpolation

existing_files: False
#specifies if preprocessed model files exist or not

#radial profiles------------------------------------------------------------------------------------------------------------
day: 4
#day within the simulation to start the time average at

height: 1000
#height in meters of the profile if analyzing a single profile

#composites-----------------------------------------------------------------------------------------------------------------

height_names: ["100", "150", "200", "250", "500", "1000", "1500", "2000", "3000", "4000", 
         "5000", "6000", "7000", "8000", "9000", "10000", "11000", "12000", "13000", "14000", "15000", "16000"]
#strings of the interpolated height levels, used to fetch particular files

height_vals: [100, 150, 200, 250, 500, 1000, 1500, 2000, 3000, 4000, 
         5000, 6000, 7000, 8000, 9000, 10000, 11000, 12000, 13000, 14000, 15000, 16000]
#the height values of the interpolated height levels