rjpbl:
    interp_latlon:
        50km:
            acme-a: "{data_path}acme-a/publish/acme.162-rjpbl.r50.L30.interp_latlon.hydro.T.nc"
            cam-se: "{data_path}cam-se/publish/cam-se.162-rjpbl.r50.L30.interp_latlon.hydro.control.T.nc"
            csu_CP: "{data_path}csu/publish/csu_CP/csu.162.r050.L30.interp_latlon.hydro.CP_default.rotated.T.nc"
            csu_LZ: "{data_path}csu/publish/csu_LZ/csu.162.r050.L30.interp_latlon.hydro.LZ_default.rotated.T.nc"
            dynamico: "{data_path}dynamico/publish/dynamico.162.50km.L30.hex.hydro.tropical_cyclone/dynamico.162.50km.L30.hex_interp_latlon.hydro.tropical_cyclone.T.nc"
            fv3_dzlow: "{data_path}fv3/publish/release_v1.2_DCMIP_dzlow/fv3.162-lsprecip.r50.L30.interp_latlon.nonhydro/fv3.162-lsprecip.r50.L30.interp_latlon.nonhydro_instant.nc"  
            fvm: "{data_path}fvm/publish/fvm.162.r50.L30.nonhydro.interp_latlon.T.nc"
            gem: "{data_path}gem/publish/Test162_RJ_r50/gem.162-rjpbl.r50.L30.interp_latlon.nonhydro.del6.t.nc"
            icon: "{data_path}icon/publish/icon.162.r50.L30.interp_latlon.nonhydro.dt200_Reed_PBL.T.nc"
            nicam: "{data_path}nicam/publish/nicam.162-rjpbl.r50.L30.interp_latlon.nonhydro.T.nc"
        25km:
            acme-a: "{data_path}acme-a/publish/acme.162-rjpbl.r25.L30.interp_latlon.hydro.T.nc"
            cam-se: "{data_path}cam-se/publish/cam-se.162-rjpbl.r25.L30.interp_latlon.hydro.control.T.nc"
            #csu_CP: "{data_path}csu/publish/csu_CP/csu.162.r025.L30.interp_latlon.hydro.CP_default.rotated.T.nc"
            #csu_LZ: "{data_path}csu/publish/csu_LZ/csu.162.r025.L30.interp_latlon.hydro.LZ_default.rotated.T.nc"
            #dynamico: "{data_path}dynamico/publish/dynamico.162.25km.L30.hex.hydro.tropical_cyclone/dynamico.162.25km.L30.hex_interp_latlon.hydro.tropical_cyclone.T.nc"
            #fv3_dzlow: "{data_path}fv3/publish/release_v1.2_DCMIP_dzlow/fv3.162-lsprecip.r25.L30.interp_latlon.nonhydro/fv3.162-lsprecip.r25.L30.interp_latlon.nonhydro_instant.nc"  
            fvm: "{data_path}fvm/publish/fvm.162.r25.L30.nonhydro.interp_latlon.T.nc"
            gem: "{data_path}gem/publish/Test162_RJ_r25/gem.162-rjpbl.r25.L30.interp_latlon.nonhydro.del6.t.nc"
            #icon: "{data_path}icon/publish/icon.162.r25.L30.interp_latlon.nonhydro.dt200_Reed_PBL.T.nc"
            nicam: "{data_path}nicam/publish/nicam.162-rjpbl.r25.L30.interp_latlon.nonhydro.T.nc"