rjpbl:
    interp_latlon:
        50km:
            cam-se: "{data_path}cam-se/publish/cam-se.162-rjpbl.r50.L30.interp_latlon.hydro.control.Z.nc"
            gem: "{data_path}gem/publish/Test162_RJ_r50/gem.162-rjpbl.r50.L30.interp_latlon.nonhydro.del6.phii.nc"
        25km:
            cam-se: "{data_path}cam-se/publish/cam-se.162-rjpbl.r25.L30.interp_latlon.hydro.control.Z.nc"
            gem: "{data_path}gem/publish/Test162_RJ_r25/gem.162-rjpbl.r25.L30.interp_latlon.nonhydro.del6.phii.nc"